version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/episode_poller"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/episode_poller/terraform"
    schedule:
      interval: "weekly"
